# Labeler rules for PRs (actions/labeler@v5 syntax)
# Docs: https://github.com/actions/labeler#common-examples

frontend:
  - changed-files:
      - any-glob-to-any-file: ['frontend/**']

backend:
  - changed-files:
      - any-glob-to-any-file: ['src/**','pom.xml']

devx:
  - changed-files:
      - any-glob-to-any-file: ['.github/**','tools/**']
