name: Auto-enable auto-merge on PRs (opt-in by label)

on:
  pull_request:
    types: [labeled, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    # Only run if the PR currently has a label named 'auto-merge'
    if: contains(toJson(github.event.pull_request.labels), 'auto-merge')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge (merge strategy)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          gh pr merge "$PR_NUMBER" --auto --merge --repo "$REPO"
