name: Auto PR on branch push

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    concurrency:
      group: auto-pr-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create or update PR and enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
        run: |
          set -e
          echo "Branch: $BRANCH"
          # Find existing PR for this branch
          PR_NUMBER=$(gh pr list --head "$BRANCH" --state open --json number -q '.[0].number' || true)
          if [ -z "$PR_NUMBER" ]; then
            TITLE="Auto PR: $BRANCH"
            BODY="This PR was automatically created from branch '$BRANCH'.\nAuto-merge will complete when required checks pass."
            gh pr create --base main --head "$BRANCH" --title "$TITLE" --body "$BODY" --repo "$REPO"
            PR_NUMBER=$(gh pr list --head "$BRANCH" --state open --json number -q '.[0].number')
          else
            echo "PR already exists: #$PR_NUMBER"
          fi

          # Enable auto-merge (merge strategy)
          gh pr merge "$PR_NUMBER" --auto --merge --repo "$REPO"

          # Optional: add labels based on paths (works with labeler)
          echo "Ensured auto-merge is enabled for PR #$PR_NUMBER"
